[features]
seeds = true
skip-lint = false
[programs.localnet]
attempt1 = "4yhK57aLadt8wc9rmqF4QWDhVHQnkCMwXP8V6H9netGZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
